CREATE TABLE parking_session (
    id uuid PRIMARY KEY,
    user_id uuid,
    spot_id bigint,
    checkin_ts timestamptz,
    checkout_ts timestamptz,
    status varchar(32) DEFAULT 'ONGOING',
    pricing_version varchar(64),
    total_amount_cents bigint,
    payment_intent_id varchar(128)
);

CREATE TABLE pricing_rule (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(128),
    json_config jsonb NOT NULL,
    effective_from timestamptz,
    effective_to timestamptz
);

ALTER TABLE parking_session ADD COLUMN license_plate varchar(64);

CREATE TABLE payment_transaction (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    payment_intent_id varchar(128) NOT NULL UNIQUE,
    session_id uuid NOT NULL,
    amount_cents bigint,
    status varchar(32),
    created_at timestamptz,
    updated_at timestamptz
);

-- Base rate (already implicitly handled)
INSERT INTO pricing_rule(name, json_config, effective_from, effective_to)
VALUES ('BASE_RATE', '{"type":"base_rate","centsPerMinute":5}', NOW(), '2099-12-31');

-- Membership discount
INSERT INTO pricing_rule(name, json_config, effective_from, effective_to)
VALUES ('PREMIUM_DISCOUNT', 
        '{"type":"membership_discount","membership":"PREMIUM","discountPercent":20}', NOW(), '2099-12-31');

-- Evening surcharge
INSERT INTO pricing_rule(name, json_config, effective_from, effective_to)
VALUES ('EVENING_SURCHARGE', 
        '{"type":"time_surcharge","startHour":18,"endHour":22,"surchargeCentsPerMinute":2}', NOW(), '2099-12-31');